title: What is your browser? Find our here.
email: hello@browserdetails.com
description: >- # this means to ignore newlines until "baseurl:"
  Find out what browser you're using, and what it's settings are.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://BrowserDetails.com" 
twitter_username: BrowserDetails
github_username:  BrowserDetails


highlighter: rouge

# Build settings
theme: minima
plugins:
  - jekyll-feed

google_tag_manager: GTM-MZD36BB
google_analytics: G-WR47C76DL8

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
